# Generated by Django 3.0.8 on 2020-07-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pokemon', models.CharField(max_length=100)),
                ('experience_growt', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('abilities', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('is_legendary', models.IntegerField()),
                ('predict_is_legendary_2', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('fuerza_IV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypePokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100)),
                ('name_type_2', models.ManyToManyField(through='api.Pokemon', to='api.TypePokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='api.TypePokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='api.TypePokemon'),
        ),
    ]
