# Generated by Django 3.0.8 on 2020-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pokemon', models.CharField(max_length=100)),
                ('experience_growt', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('abilities', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('is_legendary', models.IntegerField()),
                ('predict_is_legendary_2', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('fuerza_IV', models.IntegerField()),
                ('type1', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100)),
            ],
        ),
    ]
