# Generated by Django 3.0.8 on 2020-07-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pokemon2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon2',
            name='pokedex_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
