# Generated by Django 3.0.8 on 2020-08-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pokemon2_pokedex_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typepokemon',
            name='name_type_2',
        ),
        migrations.AddField(
            model_name='pokemon2',
            name='descripcion_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon2',
            name='descripcion_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='TypePokemon',
        ),
    ]
